version: '3'
services:
  onion:
    build: ./onion_service
    cpus: 4
    mem_limit: 2g
    volumes:
      - ./onion_service/hidden_service:/var/lib/tor/hidden_service
      - ./onion_service/torrc:/etc/tor/torrc
      - ./onion_service/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - captcha

  captcha:
    build: ./captcha_service
    cpus: 4
    mem_limit: 1g
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - tor-proxy

  redis:
    image: redis:latest
    cpus: 4
    mem_limit: 5g

  tor-proxy:
    restart: always
    image: dockage/tor-privoxy:latest
    cpus: 2
    mem_limit: 1g
